FactoryBot.define do
  factory :jobapp do
    firstname { "MyString" }
    lastname { "MyString" }
    email { "MyString" }
    phonenumber { "MyString" }
    addressline { "MyString" }
    city { "MyString" }
    state { "MyString" }
    zipcode { "MyString" }
    minor { "MyString" }
    jobtarget { "MyString" }
    jobtitle { "MyString" }
    joblocation { "MyString" }
    desiredsalary { "MyString" }
    jobtarget2 { "MyString" }
    jobtitle2 { "MyString" }
    joblocation2 { "MyString" }
    desiredsalary2 { "MyString" }
    employmentinformation { "MyString" }
    citizen { "MyString" }
    authorized { "MyString" }
    previousjugojob { "MyString" }
    previousjugojobdetails { "MyString" }
    felony { "MyString" }
    felonydetails { "MyString" }
    schoolinformation { "MyString" }
    highestlevelachieved { "MyString" }
    schoolname { "MyString" }
    reference { "MyString" }
    reffullname { "MyString" }
    relationship { "MyString" }
    refcompany { "MyString" }
    refphone { "MyString" }
    reference2 { "MyString" }
    reffullname2 { "MyString" }
    relationship2 { "MyString" }
    refcompany2 { "MyString" }
    refphone2 { "MyString" }
    previousemployment { "MyString" }
    prevcompany { "MyString" }
    jobtitle { "MyString" }
    worknumber { "MyString" }
    responsibilities { "MyString" }
    employementstartdate { "MyString" }
    employmentenddate { "MyString" }
    reasonforleaving { "MyString" }
    previousemployment2 { "MyString" }
    prevcompany2 { "MyString" }
    jobtitle2 { "MyString" }
    worknumber2 { "MyString" }
    responsibilities2 { "MyString" }
    employementstartdate2 { "MyString" }
    employmentenddate2 { "MyString" }
    reasonforleaving2 { "MyString" }
    militaryservice { "MyString" }
    branch { "MyString" }
    startdate { "MyString" }
    enddate { "MyString" }
    dischargetype { "MyString" }
    dischargeexplanation { "MyString" }
    electronicsignature { "MyString" }
  end
end
